Task: Architecture Cleanup
gnosis/gnosis-management pull request #276
Opened 2018-04-06 09:37 UTC by andre-meyer

- Fix naming structures (`routes/MarketDetail` vs `routes/marketlist`)
- Remove unnecessary relative imports to absolute imports
- Refactor out the main `Layout` Component in MarketList Route
- Fix Outcome Component to accept backwards compatible entity structure

2018-04-07 15:52 UTC, mmvsha commented
are you going to fix failing test?

2018-04-09 09:16 UTC, mmvsha commented on src/routes/MarketList/components/Markets.js
> +import Market from './Market/index'
index is not needed

2018-04-09 09:17 UTC, mmv08 requested changes

2018-04-09 09:17 UTC, mmvsha commented on src/routes/MarketList/components/index.js
> +import Filter from './Filter/index'
same here

2018-04-09 09:50 UTC, mmv08 approved these changes

2018-04-09 10:29 UTC, merged